server:
  port: 8080
management.endpoints.web.exposure.include: hystrix.stream
spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: orderModule
          uri: lb://order-service
          predicates:
            - Path=/order/**
        - id: employeeModule
          uri: lb://customer-service
          predicates:
            - Path=/customer/**
        - id: consumerModule
          uri: lb://product-service
          predicates:
            - Path=/product/**

