server:
  port: 8000
management.endpoints.web.exposure.include: hystrix.stream
spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service
#  cloud:
#    gateway:
#      routes:
#        - id: orderModule
#          uri: lb://order-service
#          predicates:
#          - Path=/order/**
#        - id: employeeModule
#          uri: lb://customer-service
#          predicates:
#          - Path=/customer/**
#        - id: consumerModule
#          uri: lb://product-service
#          predicates:
#          - Path=/product/**


#resilience4j.circuitbreaker:
#  configs:
#    default:
#      registerHealthIndicator: true
#      slidingWindowSize: 10
#      minimumNumberOfCalls: 5
#      permittedNumberOfCallsInHalfOpenState: 3
#      automaticTransitionFromOpenToHalfOpenEnabled: true
#      waitDurationInOpenState: 5s
#      failureRateThreshold: 50
#      eventConsumerBufferSize: 10
#      recordExceptions:
#        - org.springframework.web.client.HttpServerErrorException
#        - java.util.concurrent.TimeoutException
#        - java.io.IOException
#    shared:
#      slidingWindowSize: 100
#      permittedNumberOfCallsInHalfOpenState: 30
#      waitDurationInOpenState: 1s
#      failureRateThreshold: 50
#      eventConsumerBufferSize: 10
#  instances:
#    orderModule:
#      baseConfig: default